version: '3.3'

volumes:
  pg_data:
  static_backend:
  media_backend:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: semenovaliza/foodgram-backend:v1.07.2023
    env_file: .env
    volumes:
      - static_backend/:/app/static/
      - media_backend:/app/media/
  frontend:
    image: semenovaliza/foodgram-frontend:v1.07.2023
    volumes:
      - ../frontend/:/app/result_build/
    env_file: .env
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_backend:/var/html/static/
      - media_backend:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/