# Generated by Django 3.2 on 2023-04-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название ингридиента')),
                ('number', models.PositiveIntegerField(verbose_name='Количество необходимого ингридиента')),
                ('measurement_unit', models.CharField(max_length=150, verbose_name='Единицаа измерения')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
            },
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=150, unique=True, verbose_name='Цвет тега'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название тега'),
        ),
    ]
