# Generated by Django 3.2 on 2023-04-23 22:27

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230423_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='number',
            field=models.PositiveIntegerField(validators=[recipes.validators.validate_ingredient_number], verbose_name='Количество необходимого ингридиента'),
        ),
    ]
