# Generated by Django 3.2 on 2023-05-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230507_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesingredient',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
