# Generated by Django 3.2 on 2023-05-07 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_ingredients_recipesingredient_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipesingredientss', to='recipes.recipe'),
        ),
    ]
