# Generated by Django 3.2 on 2023-05-07 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipesingredient_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient'),
        ),
    ]
