# Generated by Django 3.2 on 2023-05-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipesingredient_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipesingredient',
            name='amount',
        ),
    ]
