# Generated by Django 3.2 on 2023-05-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipesingredient_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesingredient',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
