name: Foodgram workflow

on: [push] 
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install pytest
        pip install -r backend/foodgram/requirements.txt 

    - name: flake8 tests
      run: |
        python -m flake8
  
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker 
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2 
        with:
          context: backend/foodgram/
          push: true
          tags: semenovaliza/foodgram-backend:v1.05.2023

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    if: github.ref == 'refs/heads/master' 

    steps:

      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            sudo docker pull semenovaliza/foodgram-backend:v1.05.2023
            sudo docker-compose stop
            sudo docker-compose rm backend
            rm foodgram-project-react/infra/.env
            touch foodgram-project-react/infra/.env
            echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> foodgram-project-react/infra/.env
            echo DB_NAME=${{ secrets.DB_NAME }} >> foodgram-project-react/infra/.env
            echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> foodgram-project-react/infra/.env
            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> foodgram-project-react/infra/.env
            echo DB_HOST=${{ secrets.DB_HOST }} >> foodgram-project-react/infra/.env
            echo DB_PORT=${{ secrets.DB_PORT }} >> foodgram-project-react/infra/.env
            sudo docker-compose up -d
     